### ISSUE TITLE
Separate grasp generators for custom objects such as rectanguar or cylindrical objects

### ISSUE THREAD

**Issue by fivef** [davetcoleman/moveit_simple_grasps#13]
Where can I find these separate grasp generators announced in the readme? I can only find the box grasp generator in the code and it seems not to use a block size anywhere. Am I missing something?

**Comment by davetcoleman** [comment]
This will create a circle of grasps around a center point along a particular axis:
https://github.com/davetcoleman/moveit_simple_grasps/blob/indigo-devel/include/moveit_simple_grasps/simple_grasps.h#L140
