### ISSUE TITLE
unable to connect to any subscribers within 1 seconds

### ISSUE THREAD

**Issue by raphimulator** [davetcoleman/moveit_simple_grasps#17]
Hello,

I've tried using the demo code from your landing page and it works fine so far, but after trying to visualize the generated grasps, I got the following warning:
`Topic '/rviz_visual_tools' unable to connect to any subscribers within 1 seconds. It is possible initially published visual messages will be lost.`

I guess it's the same problem as this one.
https://github.com/davetcoleman/ompl_visual_tools/issues/2

Sadly, building from scatch would not be the best option, since we have a big team and we would like to keep project-setup nice and simple.

Or maybe that has nothing to do with my problem.

**Comment by raphimulator** [comment]
Okay I cloned your repo into my project and tried again. Same error.
Happens right after trying publish a box via visualtools.

**Comment by davetcoleman** [comment]
You need to add the rviz display plugin "Markers" to rviz and set it to "/rviz_visual_tools". that warning is to let you know you haven't connected the output to anything.

**Comment by raphimulator** [comment]
Thanks!
