### ISSUE TITLE
generateAxisGrasps is not very adjustable

### ISSUE THREAD

**Issue by raphimulator** [davetcoleman/moveit_simple_grasps#18]
Hi,

these simple grasps work very fine for me (thanks for that), but I have noticed that `generateAxisGrasps` doesn't really offer realistic constraints. 
Just using `grasp_axis_t` isn't really applicable for our kind of outdoor grasp-planning, since objects often don't lie on flat surfaces.

It would be  really great if there was a way to pass over custom axis, other than unit vectors. 

Also `Z Axis not implemented!`, which is sad, because it would be useful for picking up cylinders.

**Comment by raphimulator** [comment]
https://github.com/davetcoleman/moveit_simple_grasps/pull/19

**Comment by davetcoleman** [comment]
Good point, thanks!

p.s. would you be interested in taking over maintainer-ship of this package?

**Comment by davetcoleman** [comment]
This was merged
