### ISSUE TITLE
problem of loading config file when running grasp_test.launch

### ISSUE THREAD

**Issue by YantianZha** [davetcoleman/moveit_simple_grasps#20]
Hi,
When roslaunching the grasp_test.launch, I met error: "Joint 'right_gripper_l_finger_joint' not found in model 'baxter'. So I guess I need to use my own end-effector file? All baxter config files are in baxter_moveit_config package, but I could not find the yaml like the default "baxter_grasp_data.yaml" in baxter_moveit_config package?
Could you give me some hints about where can I find a similar file (like "baxter_grasp_data.yaml") or how to generate it without affecting original baxter config system? 

Thanks very much!

**Comment by davetcoleman** [comment]
Hi Yantian,

I'm sorry, but I cannot maintain this package anymore. We actually made a much more robust one internally and my efforts are focused on that. I've added a warning at the top of the README.md to help future users:

```
# SUPPORT FOR THIS PACKAGE HAS ENDED
Sorry, too many things to maintain. Use at your own risk.
```
