### ISSUE TITLE
Install with apt-get install

### ISSUE THREAD

**Issue by lluissalord** [davetcoleman/moveit_simple_grasps#24]
It seems that when you install this package with the command `sudo apt-get install ros-indigo-moveit-simple-grasps` is not with one of the lasts versions. There isn't the folder config and others commits.

If you can update that it would be perfect, thank you so much.

**Comment by davetcoleman** [comment]
I released 1.3.1, which has all the latest changes. It could be I didn't setup the CMake to install those folders, however. As the README.md says, however, this package is end of life so I'm not really supporting it anymore. I suggest you just build this package from source...
